"""Shared physical and default constants used across nmrkit.

The gyromagnetic ratios below follow the IUPAC Recommendations 2001 table of
standardized nuclear spin data. The proton gyromagnetic ratio is also
consistent with the 2022 CODATA/NIST value within the precision needed for
routine NMR planning.
"""

from math import pi

GAUSS_PER_TESLA = 10_000.0
CENTIMETERS_PER_METER = 100.0

TESLA_PER_METER_PER_GAUSS_PER_CENTIMETER = CENTIMETERS_PER_METER / GAUSS_PER_TESLA
GAUSS_PER_CENTIMETER_PER_TESLA_PER_METER = (
    GAUSS_PER_TESLA / CENTIMETERS_PER_METER
)

PROTON_GYROMAGNETIC_RATIO_RAD_S_T = 2.0 * pi * 42.5764e6

GYROMAGNETIC_RATIOS_RAD_S_T = {
    "1H": PROTON_GYROMAGNETIC_RATIO_RAD_S_T,
    "13C": 2.0 * pi * 10.7084e6,
    "15N": -2.0 * pi * 4.316e6,
    "19F": 2.0 * pi * 40.052e6,
    "31P": 2.0 * pi * 17.235e6,
}

DEFAULT_DOSY_TARGET_ATTENUATION = 0.05
DEFAULT_DOSY_GRADIENT_START_FRACTION = 0.02
DEFAULT_DOSY_GRADIENT_STOP_FRACTION = 0.95
DEFAULT_DOSY_GRADIENT_STEPS = 16
DEFAULT_DOSY_DIFFUSION_TIME_S = 0.050
DEFAULT_DOSY_GRADIENT_DURATION_S = 0.002


__all__ = [
    "CENTIMETERS_PER_METER",
    "DEFAULT_DOSY_DIFFUSION_TIME_S",
    "DEFAULT_DOSY_GRADIENT_DURATION_S",
    "DEFAULT_DOSY_GRADIENT_START_FRACTION",
    "DEFAULT_DOSY_GRADIENT_STEPS",
    "DEFAULT_DOSY_GRADIENT_STOP_FRACTION",
    "DEFAULT_DOSY_TARGET_ATTENUATION",
    "GAUSS_PER_CENTIMETER_PER_TESLA_PER_METER",
    "GAUSS_PER_TESLA",
    "GYROMAGNETIC_RATIOS_RAD_S_T",
    "PROTON_GYROMAGNETIC_RATIO_RAD_S_T",
    "TESLA_PER_METER_PER_GAUSS_PER_CENTIMETER",
]
